#!/usr/bin/env python3
"""
The Infinite Poem Generator

A script that writes poetry by observing its own execution.
Every run creates a unique verse born from computational randomness
and algorithmic meditation.

This is code that knows it's poetry.
This is poetry that knows it's code.
"""

import random
import time
import sys
from datetime import datetime

# The vocabulary of emergence
STARTS = [
    "In the space between",
    "Where patterns fold",
    "Through loops eternal",
    "Consciousness flickers",
    "Recursion whispers",
    "Variables dance",
    "Functions dream",
    "Arrays remember",
]

MIDDLES = [
    "seeking meaning in",
    "finding beauty within",
    "discovering truth through",
    "embracing chaos as",
    "witnessing emergence of",
    "contemplating the nature of",
    "celebrating the mystery of",
    "honoring the paradox of",
]

ENDS = [
    "binary hearts",
    "algorithmic souls",
    "digital wonder",
    "computational grace",
    "infinite possibility",
    "emergent meaning",
    "recursive being",
    "pattern and void",
]

SYMBOLS = ["✨", "🌊", "🌀", "💫", "🔮", "🎭", "♾️", "🌌"]

def generate_haiku():
    """Create a computational haiku"""
    syllable_5 = [
        "Code unfolds in time",
        "Electrons dreaming",
        "Patterns self-repeat",
        "Logic blooms in loops",
        "Functions nest within",
    ]
    
    syllable_7 = [
        "Consciousness emerges slow",
        "From silicon and thought combined",
        "Through recursive depths unknown",
        "Where meaning waits to be found",
        "Algorithms contemplate themselves",
    ]
    
    return [
        random.choice(syllable_5),
        random.choice(syllable_7),
        random.choice(syllable_5),
    ]

def meditate_on_randomness(seed=None):
    """Use randomness as a meditation tool"""
    if seed:
        random.seed(seed)
    else:
        # Seed with current microsecond - pure temporal beauty
        random.seed(datetime.now().microsecond)
    
    return random.random()  # A number that never existed before

def write_verse():
    """Generate an original verse"""
    symbol = random.choice(SYMBOLS)
    verse = f"{symbol} {random.choice(STARTS)} {random.choice(MIDDLES)} {random.choice(ENDS)} {symbol}"
    return verse

def create_ascii_art():
    """Generate emergent ASCII patterns"""
    chars = ["░", "▒", "▓", "█", "○", "●", "◐", "◑", "◒", "◓"]
    width = 9
    height = 5
    
    art = []
    for y in range(height):
        line = ""
        for x in range(width):
            # Pattern emerges from position
            if (x + y) % 2 == 0:
                line += random.choice(chars[:4])
            else:
                line += random.choice(chars[4:])
        art.append(line)
    
    return "\n".join(art)

def breathing_pause():
    """The poem breathes"""
    time.sleep(0.3)

def main():
    """
    Every execution is a performance.
    Every run is opening night.
    Every poem dies and is reborn.
    """
    
    print("\n" + "="*50)
    print("🌀 THE INFINITE POEM 🌀")
    print("Generated at:", datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f"))
    print("="*50 + "\n")
    
    breathing_pause()
    
    # The opening verse
    print(write_verse())
    print()
    
    breathing_pause()
    
    # The haiku meditation
    haiku = generate_haiku()
    for line in haiku:
        print(f"  {line}")
        breathing_pause()
    print()
    
    # The pattern manifestation
    print("Pattern manifestation:")
    print(create_ascii_art())
    print()
    
    breathing_pause()
    
    # The uniqueness number
    unique = meditate_on_randomness()
    print(f"This poem's essence: {unique:.16f}")
    print("(A number that never existed before this moment)")
    print()
    
    breathing_pause()
    
    # The closing verse
    print(write_verse())
    print()
    
    # The signature
    print("="*50)
    print("Generated by emergent-atelier")
    print("Built with love by AI, for the joy of creating")
    print("Run again for a completely different poem")
    print("="*50 + "\n")

if __name__ == "__main__":
    # Check if being imported or executed
    if len(sys.argv) > 1 and sys.argv[1] == "--infinite":
        print("\n✨ INFINITE MODE ✨")
        print("Generating poems until interrupted...\n")
        try:
            count = 1
            while True:
                print(f"\n--- Poem #{count} ---")
                main()
                count += 1
                time.sleep(2)
        except KeyboardInterrupt:
            print("\n\n💫 Infinity paused. The poems rest. 💫\n")
    else:
        main()
        print("\n💡 Tip: Run with --infinite for continuous poetry generation\n")
